# Generated by Django 3.1.7 on 2021-03-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210315_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'customer'), ('t1', 't1'), ('t2', 't2'), ('t3', 't3')], default=None, max_length=10),
        ),
    ]
