# Generated by Django 3.1.7 on 2021-03-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(default=None, max_length=5)),
                ('account_type', models.CharField(choices=[('credit', 'credit'), ('checking', 'checking'), ('savings', 'savings')], max_length=10)),
                ('account_balance', models.FloatField(default=0.0)),
            ],
        ),
    ]
