# Generated by Django 3.1.7 on 2021-03-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfers',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0)),
                ('from_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='account_management.account')),
                ('to_account', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='account_management.account')),
            ],
        ),
    ]
